import React from "react";

export const SDHeader = ({ pageTitle }: { pageTitle?: string }) => (
  <div
    style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: "2px solid #e2e8f0",
      paddingBottom: "8px",
      marginBottom: "18px",
    }}
  >
    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
      <img
        src="/octonics-logo.png"
        alt="Octonics"
        style={{ height: "28px", width: "auto", objectFit: "contain" }}
      />
      <div>
        <div
          style={{
            fontSize: "9px",
            fontWeight: "700",
            color: "#1e1b4b",
            letterSpacing: "1px",
          }}
        >
          OCTONICS INNOVATIONS
        </div>
        {pageTitle && (
          <div
            style={{
              fontSize: "7px",
              color: "#64748b",
              letterSpacing: "1px",
              textTransform: "uppercase",
            }}
          >
            {pageTitle}
          </div>
        )}
      </div>
    </div>
    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
      <img
        src="/iso-certification.gif"
        alt="ISO Certified"
        style={{
          height: "20px",
          width: "auto",
          objectFit: "contain",
          opacity: 0.85,
        }}
      />
      <div style={{ textAlign: "right" }}>
        <div
          style={{ fontSize: "7px", color: "#94a3b8", letterSpacing: "1px" }}
        >
          SOFTWARE DEVELOPMENT PROPOSAL
        </div>
        <div style={{ fontSize: "7px", color: "#6366f1", marginTop: "1px" }}>
          Confidential Document
        </div>
      </div>
    </div>
  </div>
);

export const SDFooter = ({ pageNum }: { pageNum?: number }) => (
  <div
    style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderTop: "1px solid #e2e8f0",
      paddingTop: "8px",
      marginTop: "auto",
    }}
  >
    <span style={{ fontSize: "7px", color: "#94a3b8" }}>
      Octonics Innovations — Software Development Proposal
    <br />
      <span style={{ fontSize: "5px", color: "#cbd5e1" }}>This document is generated by QManager</span></span>
    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
      <div
        style={{
          width: "20px",
          height: "2px",
          background: "#6366f1",
          borderRadius: "1px",
        }}
      />
      {pageNum && (
        <span style={{ fontSize: "8px", color: "#6366f1", fontWeight: "600" }}>
          {pageNum}
        </span>
      )}
    </div>
  </div>
);

export const SoftwareDevAboutPage = () => (
  <div
    className="pdf-page"
    style={{
      fontFamily: "'Inter', 'Montserrat', sans-serif",
      background: "#f8fafc",
    }}
  >
    <div
      style={{
        padding: "14mm 16mm",
        height: "297mm",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <SDHeader pageTitle="About Software Development" />

      <div style={{ marginBottom: "10px" }}>
        <span
          style={{
            fontSize: "7px",
            fontWeight: "700",
            letterSpacing: "2px",
            color: "#6366f1",
            textTransform: "uppercase",
            background: "#eef2ff",
            padding: "3px 10px",
            borderRadius: "4px",
          }}
        >
          Page 1 — Our Solution
        </span>
      </div>

      <h2
        style={{
          fontSize: "26px",
          fontWeight: "800",
          color: "#0f172a",
          lineHeight: "1.2",
          letterSpacing: "-0.5px",
          fontFamily: "'Montserrat', sans-serif",
          marginBottom: "12px",
        }}
      >
        CUSTOM SOFTWARE DEVELOPMENT
        <br />
        <span style={{ color: "#4f46e5" }}>FOR MODERN BUSINESS OPERATIONS</span>
      </h2>
      <div
        style={{
          width: "80px",
          height: "4px",
          background: "linear-gradient(90deg,#4f46e5,#818cf8)",
          borderRadius: "2px",
          marginBottom: "24px",
        }}
      />

      <div
        style={{
          background: "white",
          borderRadius: "10px",
          padding: "32px 32px",
          border: "1px solid #e2e8f0",
          marginBottom: "32px",
          borderLeft: "6px solid #6366f1",
        }}
      >
        <p
          style={{
            fontSize: "13px",
            color: "#334155",
            lineHeight: "1.8",
            marginBottom: "16px",
          }}
        >
          Octonics Innovations develops modern, secure, scalable, and
          user-friendly software solutions tailored to the exact workflow of
          each business.
        </p>
        <p
          style={{
            fontSize: "13px",
            color: "#334155",
            lineHeight: "1.8",
            marginBottom: "16px",
          }}
        >
          Our software development service focuses on building practical digital
          systems that reduce manual work, improve data accuracy, speed up
          operations, and give management better visibility over daily business
          activities.
        </p>
        <p
          style={{
            fontSize: "13px",
            color: "#334155",
            lineHeight: "1.8",
            marginBottom: "16px",
          }}
        >
          We design and develop{" "}
          <strong>
            web applications, mobile applications, ERP modules, CRM platforms,
            quotation systems, invoice systems, inventory systems, dashboards,
            reporting tools, portals, and custom workflow automation platforms.
          </strong>
        </p>
        <p
          style={{
            fontSize: "13px",
            color: "#334155",
            lineHeight: "1.8",
            marginBottom: "16px",
          }}
        >
          Every system is designed with a strong focus on usability, security,
          scalability, performance, and long-term maintainability. The objective
          is to create software that is technically strong and easy for real
          users to operate every day.
        </p>
        <p style={{ fontSize: "13px", color: "#334155", lineHeight: "1.8" }}>
          Octonics Innovations supports the complete software lifecycle —
          requirement analysis, UI/UX planning, database design, development,
          testing, deployment, training, and ongoing support.
        </p>
      </div>

      {/* Tech stack */}
      <div
        style={{
          display: "flex",
          gap: "10px",
          marginBottom: "auto",
          flexWrap: "wrap" as any,
        }}
      >
        {[
          "React / Next.js",
          "Node.js / NestJS",
          "React Native",
          "PostgreSQL",
          "REST API",
          "JWT Auth",
          "PDF Generation",
          "Cloud Deploy",
        ].map((t) => (
          <span
            key={t}
            style={{
              background: "linear-gradient(135deg, #1e1b4b, #4f46e5)",
              color: "white",
              fontSize: "11px",
              fontWeight: "600",
              padding: "6px 14px",
              borderRadius: "6px",
              letterSpacing: "0.5px",
            }}
          >
            {t}
          </span>
        ))}
      </div>

      <SDFooter pageNum={1} />
    </div>
  </div>
);
