import React from "react";

export const SDHeader = ({ pageTitle }: { pageTitle?: string }) => (
  <div
    style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: "2px solid #e2e8f0",
      paddingBottom: "8px",
      marginBottom: "18px",
    }}
  >
    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
      <img
        src="/octonics-logo.png"
        alt="Octonics"
        style={{ height: "28px", width: "auto", objectFit: "contain" }}
      />
      <div>
        <div
          style={{
            fontSize: "9px",
            fontWeight: "700",
            color: "#1e1b4b",
            letterSpacing: "1px",
          }}
        >
          OCTONICS INNOVATIONS
        </div>
        {pageTitle && (
          <div
            style={{
              fontSize: "7px",
              color: "#64748b",
              letterSpacing: "1px",
              textTransform: "uppercase",
            }}
          >
            {pageTitle}
          </div>
        )}
      </div>
    </div>
    <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
      <img
        src="/iso-certification.gif"
        alt="ISO Certified"
        style={{
          height: "20px",
          width: "auto",
          objectFit: "contain",
          opacity: 0.85,
        }}
      />
      <div style={{ textAlign: "right" }}>
        <div
          style={{ fontSize: "7px", color: "#94a3b8", letterSpacing: "1px" }}
        >
          SOFTWARE DEVELOPMENT PROPOSAL
        </div>
        <div style={{ fontSize: "7px", color: "#6366f1", marginTop: "1px" }}>
          Confidential Document
        </div>
      </div>
    </div>
  </div>
);

export const SDFooter = ({ pageNum }: { pageNum?: number }) => (
  <div
    style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderTop: "1px solid #e2e8f0",
      paddingTop: "8px",
      marginTop: "auto",
    }}
  >
    <span style={{ fontSize: "7px", color: "#94a3b8" }}>
      Octonics Innovations — Software Development Proposal
    <br />
      <span style={{ fontSize: "5px", color: "#cbd5e1" }}>This document is generated by QManager</span></span>
    <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
      <div
        style={{
          width: "20px",
          height: "2px",
          background: "#6366f1",
          borderRadius: "1px",
        }}
      />
      {pageNum && (
        <span style={{ fontSize: "8px", color: "#6366f1", fontWeight: "600" }}>
          {pageNum}
        </span>
      )}
    </div>
  </div>
);

export const SoftwareDevAboutPage = () => (
  <div
    className="pdf-page"
    style={{
      fontFamily: "'Inter', 'Montserrat', sans-serif",
      background: "#f8fafc",
    }}
  >
    <div
      style={{
        padding: "14mm 16mm",
        height: "297mm",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <SDHeader pageTitle="About Octonics Innovations" />

      <div style={{ marginBottom: "10px" }}>
        <span
          style={{
            fontSize: "7px",
            fontWeight: "700",
            letterSpacing: "2px",
            color: "#6366f1",
            textTransform: "uppercase",
            background: "#eef2ff",
            padding: "3px 10px",
            borderRadius: "4px",
          }}
        >
          Page 2 — Company Profile
        </span>
      </div>

      <h2
        style={{
          fontSize: "26px",
          fontWeight: "800",
          color: "#0f172a",
          lineHeight: "1.2",
          letterSpacing: "-0.5px",
          fontFamily: "'Montserrat', sans-serif",
          marginBottom: "12px",
        }}
      >
        OCTONICS INNOVATIONS
        <br />
        <span style={{ color: "#4f46e5" }}>EMPOWERING DIGITAL TRANSFORMATION</span>
      </h2>
      <div
        style={{
          width: "80px",
          height: "4px",
          background: "linear-gradient(90deg,#4f46e5,#818cf8)",
          borderRadius: "2px",
          marginBottom: "24px",
        }}
      />

      <div
        style={{
          background: "white",
          borderRadius: "10px",
          padding: "24px",
          border: "1px solid #e2e8f0",
          marginBottom: "24px",
          borderLeft: "6px solid #6366f1",
        }}
      >
        <h3 style={{ fontSize: "14px", fontWeight: "700", color: "#1e1b4b", marginBottom: "8px", fontFamily: "'Montserrat', sans-serif" }}>About Us</h3>
        <p
          style={{
            fontSize: "11px",
            color: "#334155",
            lineHeight: "1.7",
            marginBottom: "16px",
          }}
        >
          Octonics Innovations is a premier Kuwait-based technology solutions provider specializing in Software Development, Smart Automation, and IT Infrastructure. We are an ISO-certified organization dedicated to delivering robust, scalable, and highly secure digital solutions tailored to meet the dynamic needs of modern businesses.
        </p>

        <h3 style={{ fontSize: "14px", fontWeight: "700", color: "#1e1b4b", marginBottom: "8px", fontFamily: "'Montserrat', sans-serif" }}>Our Vision</h3>
        <p
          style={{
            fontSize: "11px",
            color: "#334155",
            lineHeight: "1.7",
            marginBottom: "0px",
          }}
        >
          To be the leading catalyst for digital transformation in the region, empowering organizations through innovative technology, seamless automation, and intelligent software systems that drive operational excellence and sustainable growth.
        </p>
      </div>

      <h3 style={{ fontSize: "16px", fontWeight: "800", color: "#0f172a", marginBottom: "12px", fontFamily: "'Montserrat', sans-serif" }}>Our Core Expertise</h3>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "12px",
          marginBottom: "auto",
        }}
      >
        {[
          { icon: "💻", title: "Custom Software Development", desc: "Web applications, ERP modules, CRM platforms, and tailored business software." },
          { icon: "📱", title: "Mobile App Development", desc: "Native and cross-platform mobile applications for iOS and Android devices." },
          { icon: "🏢", title: "Building & Home Automation", desc: "KNX-certified smart solutions for lighting, climate, and security control." },
          { icon: "🌐", title: "IT Infrastructure & Networking", desc: "Robust data networks, server deployments, and enterprise connectivity." },
          { icon: "🔒", title: "Surveillance & Access Control", desc: "Advanced CCTV systems, biometrics, and secure facility access management." },
          { icon: "☁️", title: "Cloud & DevOps Services", desc: "Secure cloud hosting, CI/CD pipelines, and scalable application deployment." },
        ].map((skill, index) => (
          <div key={index} style={{ background: "white", padding: "14px", borderRadius: "8px", border: "1px solid #e2e8f0", display: "flex", gap: "10px" }}>
            <div style={{ fontSize: "24px" }}>{skill.icon}</div>
            <div>
              <div style={{ fontSize: "11px", fontWeight: "700", color: "#1e1b4b", marginBottom: "4px" }}>{skill.title}</div>
              <div style={{ fontSize: "9px", color: "#64748b", lineHeight: "1.5" }}>{skill.desc}</div>
            </div>
          </div>
        ))}
      </div>

      <SDFooter pageNum={2} />
    </div>
  </div>
);
